### ISSUE TITLE
Password error

### ISSUE THREAD

**Issue by squidpunch** [HipByte/motion-appstore#1]
found this gem and looking forward to being able to use it.  I noticed the following error when trying to validate my build, am I missing a step?

```
Validate: ./build/iPhoneOS-7.1-Release/Hello 200.ipa
Enter your password: 
altool: option requires an argument -- p
2015-01-05 15:34:34.298 altool[86916:10649385] *** Error: Must provide username and/or password.
```

**Comment by Watson1978** [comment]
This plugin uses Application Loader's tool which require a password to login Apple developer center.

1) If you would add an account in Xcode's preference, this plugin retrives a password from keychain which was created by Xcode. if missing a keychain with some reason, you can remove and add account into Xcode's preference, then keychain will be created.
2) if it can't a password in keychain, you can input a password in terminal prompt which you met. You should input a valid password to login Apple developer center.

**Comment by Watson1978** [comment]
Maybe, I need some test case more. 
Can you tell me your Xcode version and your inputted command (i.e. account name) ?

**Comment by Watson1978** [comment]
I found a bug, maybe, it might be related to your problem.
https://github.com/Watson1978/motion-appstore/commit/a7e53493876d6dc71af44d595ea897c23cc194e1

Could you try with master changing?

**Comment by squidpunch** [comment]
@Watson1978 :+1: that seems to be it, thanks so much, this gem is awesome!

**Comment by squidpunch** [comment]
working with the changes suggested in master

**Comment by Watson1978** [comment]
Thank you for your confirming.
I will release new version which has the changing :)
