### ISSUE TITLE
Cannot paste password in

### ISSUE THREAD

**Issue by iwarshak** [HipByte/motion-appstore#2]
I cannot seem to paste in my password when doing validate and upload.

**Comment by Watson1978** [comment]
Thank you. I will investigate the problem.
I recommend you would use keychain following operation in https://github.com/HipByte/motion-appstore/issues/1#issuecomment-68816124

**Comment by Watson1978** [comment]
Sorry for late replying.
I've tried your issue on Yosemite.
However, I can't reproduce, I was able to paste my password in prompt.

**Comment by markrickert** [comment]
@iwarshak You have to hit the enter button twice. So wait for the prompt, paste and hit `enter` `enter` and it should work.

**Comment by Watson1978** [comment]
I can't reproduce this issue. So closed
