### ISSUE TITLE
Error invalid image path

### ISSUE THREAD

**Issue by benjreinhart** [HipByte/motion-appstore#5]
I cannot find any information on why I am getting the following error. The only thing I can find is XCode users having a similar issue, but using XCode to solve it. Has anyone encountered this issue? Do you know what I have to do for this? I checked every one of those paths by `open`ing them and it was exactly as I expected.

```
Product (master) λ motion validate my@email.com
Validate: ./build/iPhoneOS-7.1-Release/Product.ipa
✗ Invalid Image Path - No image found at the path referenced under key 'CFBundleIconFiles': '/Users/me/Desktop/product/resources/icon/58.png'
✗ Invalid Image Path - No image found at the path referenced under key 'CFBundleIconFiles': '/Users/me/Desktop/product/resources/icon/87.png'
✗ Invalid Image Path - No image found at the path referenced under key 'CFBundleIconFiles': '/Users/me/Desktop/product/resources/icon/120.png'
✗ Invalid Image Path - No image found at the path referenced under key 'CFBundleIconFiles': '/Users/me/Desktop/product/resources/icon/180.png'
✗ Invalid Image Path - No image found at the path referenced under key 'CFBundleIcons': '/Users/me/Desktop/product/resources/icon/58.png'
✗ Invalid Image Path - No image found at the path referenced under key 'CFBundleIcons': '/Users/me/Desktop/product/resources/icon/87.png'
✗ Invalid Image Path - No image found at the path referenced under key 'CFBundleIcons': '/Users/me/Desktop/product/resources/icon/120.png'
✗ Invalid Image Path - No image found at the path referenced under key 'CFBundleIcons': '/Users/me/Desktop/product/resources/icon/180.png'
✗ Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0.
```

Any help is much appreciated.

**Comment by markrickert** [comment]
Try putting your icons in the root of the resources folder named `icon-soze.png` and use this in your `Rakefile`:

``` ruby
app.icons = Dir.glob("resources/icon*.png").map{|icon| icon.split("/").last}
```

OR use some variation of this if you want to keep them in a subfolder:

``` ruby
app.icons = Dir.glob("resources/icon/*.png").map{|icon| "icon/" << icon.split("/").last}
```

You might also be missing some versions of the icon required by iOS. I'd suggest using [iConify](https://itunes.apple.com/us/app/iconify/id416289784?mt=12) and give it your 1024x1024 image and it will generate all the correct sizes for you.

**Comment by benjreinhart** [comment]
Thanks for the quick reply!

Yeah, it looks like it had to do with the filename, not the path. According to the options [here](http://www.rubymotion.com/developers/guides/manuals/cocoa/project-management/#_ios_options), the filename should be in a certain format and mine was not.

Apologize for the issue, I didn't find that until after I opened the issue.

**Comment by markrickert** [comment]
:+1: Glad you got it figured out! Good luck with the app!
