### ISSUE TITLE
Transporter not found error after Xcode 6.3 update

### ISSUE THREAD

**Issue by squidpunch** [HipByte/motion-appstore#6]
Getting this after updating Xcode 6.3

> Transporter not found at path: /usr/local/itms/bin/iTMSTransporter.  You should reinstall the application.

I also got this error in the Application Loader application, but after reinstalling it I was able to upload my application.  motion upload still has this error

**Comment by Watson1978** [comment]
I've used Xcode 6.3. However, I can't reproduced your problem.

```
$ motion validate 'sfujita04@gmail.com'
Validate: ./build/iPhoneOS-8.2-Release/BitWatch.ipa
✓ No errors validating archive at ./build/iPhoneOS-8.2-Release/BitWatch.ipa
$ xcodebuild -version
Xcode 6.3
Build version 6D570
```

In my env, `iTMSTransporter` is contained in `Application Loader.app`.
Can you confirm that it is existing?

```
$ find /Applications/Xcode.app -name "iTMSTransporter"
/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter
/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/share/iTMSTransporter.woa/Contents/MacOS/iTMSTransporter
/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/share/iTMSTransporter.woa/iTMSTransporter
```

And `iTMSTransporter` has used Java. Can you confirm the version you are using?

```
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```

I've used Java in http://support.apple.com/kb/DL1572

Thank you.

**Comment by squidpunch** [comment]
Thanks Watson. I'll check these things when I get into the office this morning.  Thanks for checking, sounds like a problem with my system then, but I will confirm

**Comment by squidpunch** [comment]
> In my env, iTMSTransporter is contained in Application Loader.app.
> Can you confirm that it is existing?

```
find /Applications/Xcode.app -name "iTMSTransporter"
/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter
/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/share/iTMSTransporter.woa/Contents/MacOS/iTMSTransporter
/Applications/Xcode.app/Contents/Applications/Application Loader.app/Contents/itms/share/iTMSTransporter.woa/iTMSTransporter
```

> And iTMSTransporter has used Java. Can you confirm the version you are using?

```
java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```

the interesting thing is, validate works, but upload does not.... (in this example I am getting a validation error because I am trying to upload one uploaded before - but the same will happen for a binary that passes validation)

```
motion validate 'squid+punch@meyouhealth.com'
Validate: ./build/iPhoneOS-7.1-Release/Hello 200 STG.ipa
✗ Redundant Binary Upload. There already exists a binary upload with build '1.3.3' for version '214'
```

```
motion upload 'squid+punch@meyouhealth.com'
Upload: ./build/iPhoneOS-7.1-Release/Hello 200 STG.ipa
✗ Transporter not found at path: /usr/local/itms/bin/iTMSTransporter.  You should reinstall the application.
```

**Comment by squidpunch** [comment]
@Watson1978 however, this helped me figure out what was going on here - i just need a symlink in `/usr/local/itms/`

added the symlink, and now its working again.

**Comment by markrickert** [comment]
for the lazy:

``` bash
mkdir -p /usr/local/itms/bin

ln -s /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/bin/iTMSTransporter /usr/local/itms/bin/iTMSTransporter
```

**Comment by squidpunch** [comment]
@markrickert yeah pretty sure I had to do something like that :+1:  (I definitely remember the symlink part at least)
