### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by travisvalentine** [HipByte/motion-appstore#8]
I've been attempting to use this to validate my .ipa hoping that it would surface some information that could point me to why my binary is wrong. However, every time I run `motion validate APP_ID`, I get nothing. Sample output:

```
$ motion validate APP_ID
Validate: ./build/iPhoneOS-9.0-Release/APP_NAME.ipa
Enter your password: $
```

Is this a known issue or am I doing something wrong?

**Comment by Watson1978** [comment]
It is right.
If you want to avoid inputting your password, you can do by resisting password in keychain (Please see https://github.com/HipByte/motion-appstore/blob/master/README.md#password-management)

**Comment by travisvalentine** [comment]
@Watson1978 Thanks for the quick reply! I added my password to keychain, actually, yet I'm still prompted for it. Here's the output after I try to re-add it:

```
$ security add-internet-password -a EMAIL -j default -r htps -s idmsa.apple.com -w PASSWORD -T /usr/bin/security
security: SecKeychainAddInternetPassword <NULL>: The specified item already exists in the keychain.
```

On my original issue though, if the output above is correct would you like me to update the README to reflect the fact that the user shouldn't expect feedback from from the `validate` command? The README suggests I'd see something like:

```
✓ No errors validating archive at ... .ipa
```

But I don't see that. I'm just prompted for my password then get kicked back out to my prompt.

**Comment by travisvalentine** [comment]
Actually, never mind. I now get the feedback. I was using `motion validate iTunes_app_id`. When in fact I should use `motion validate email`.

**Comment by andrewhavens** [comment]
I came across this as well. There is no output following password input when using the wrong email/password combination.

**Comment by Watson1978** [comment]
This plugin just provides CLI interface for Application Loader.app which is included in Xcode.app.
If Application Loader.app is working in your env, this plugin should be worked.

**Comment by Watson1978** [comment]
When I inputted wrong email/password, the plugin show the following message in my env. Seems it worked well.

```
$ motion validate sfujita@gmail.com
Validate: ./build/iPhoneOS-9.1-Release/BitWatch.ipa
Enter your password:
✗ Error: Unable to validate your application. Your Apple ID or password was entered incorrectly.
```
